### ISSUE TITLE
Slow data reading / writing?

### ISSUE THREAD

**Issue by m-schillinger** [RupaKurinchiVendhan/WiSoSuper#1]
Hello, I am trying to use your data-jupyter notebook for downloading the wind data. I installed h5pyd and requested an API key. But still, writing the data for each timestep takes several seconds and downloading all ~15000 steps would take many hours, if not days. 
Did you experience the same? any advice how to speed it up? 
Thank you very much.

**Comment by RupaKurinchiVendhan** [comment]
It helps to follow these instructions: https://github.com/NREL/hsds-examples/blob/master/notebooks/01_WTK_introduction.ipynb.
