### ISSUE TITLE
how to convert output image to wind values

### ISSUE THREAD

**Issue by guoanby** [RupaKurinchiVendhan/WiSoSuper#2]
Hi, I want to get the output wind values rather the wind picture. The output should be a picture like .png file. How did you convert a picture to a definite array.
Thank you very much.

**Comment by RupaKurinchiVendhan** [comment]
Hi! Thanks for your question. You can use this data to train your models on the raw data. These are .npy files with arrays for wind speeds that correspond to the ua and va components. Here's the link: https://data.caltech.edu/records/czs3p-5ss80
